### ISSUE TITLE
Language compatibility shown from TSModuleInfo?

### ISSUE THREAD

**Issue by wookayin** [RRethy/nvim-treesitter-endwise#10]
Just a simple question.

My understanding is that this plugin supports lua, vimscript, and ruby only, but `:TSModuleInfo` says that it is compatible with many other languages. Is this intended or just can I simply ignore it?

![image](https://user-images.githubusercontent.com/1009873/152699186-4b9c6294-c52d-47bc-a30b-cab2bbf76fa3.png)

**Comment by RRethy** [comment]
Yea that was a side-effect of supporting nested languages (ruby codeblock in markdown), we removed `is_supported` from our tree-sitter module declaration because it was a bit tricky. I add it back and now it'll look through both `endwise.scm` and `injections.scm` to be a bit smarter about which languages support it.

**Comment by wookayin** [comment]
After the update (59c8a6e), I see the following error on `:TSModuleInfo`:

```
E5108: Error executing lua ...493d1/share/nvim/runtime/lua/vim/treesitter/language.lua:25: no parser for 'markdown' language, see :help treesitter-parsers 
stack traceback:
        [C]: in function 'error'
        ...493d1/share/nvim/runtime/lua/vim/treesitter/language.lua:25: in function 'require_language'
        ...-d0493d1/share/nvim/runtime/lua/vim/treesitter/query.lua:166: in function 'get_query'
        ...im/plugged/nvim-treesitter/lua/nvim-treesitter/query.lua:91: in function 'get_query'
        .../nvim-treesitter-endwise/lua/nvim-treesitter-endwise.lua:23: in function 'has_nested_endwise_language'
        .../nvim-treesitter-endwise/lua/nvim-treesitter-endwise.lua:25: in function 'has_nested_endwise_language'
        .../nvim-treesitter-endwise/lua/nvim-treesitter-endwise.lua:25: in function 'is_supported'
        .../plugged/nvim-treesitter/lua/nvim-treesitter/configs.lua:349: in function 'is_enabled'
        ...vim/plugged/nvim-treesitter/lua/nvim-treesitter/info.lua:80: in function 'append_module_table'
        ...vim/plugged/nvim-treesitter/lua/nvim-treesitter/info.lua:113: in function 'print_info_modules'
        ...vim/plugged/nvim-treesitter/lua/nvim-treesitter/info.lua:144: in function 'run'
        [string ":lua"]:1: in main chunk
```

**Comment by wookayin** [comment]
I didn't have TS markdown module installed, but even without that installed there shouldn't be an error.

After having markdown module installed, I get another error:

```
E5108: Error executing lua ...-d0493d1/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 10
stack traceback:
        [C]: in function '_ts_parse_query'
        ...-d0493d1/share/nvim/runtime/lua/vim/treesitter/query.lua:172: in function 'get_query'
        ...im/plugged/nvim-treesitter/lua/nvim-treesitter/query.lua:91: in function 'get_query'
        .../nvim-treesitter-endwise/lua/nvim-treesitter-endwise.lua:23: in function 'is_supported'
        .../plugged/nvim-treesitter/lua/nvim-treesitter/configs.lua:349: in function 'is_enabled'
        ...vim/plugged/nvim-treesitter/lua/nvim-treesitter/info.lua:80: in function 'append_module_table'
        ...vim/plugged/nvim-treesitter/lua/nvim-treesitter/info.lua:113: in function 'print_info_modules'
        ...vim/plugged/nvim-treesitter/lua/nvim-treesitter/info.lua:144: in function 'run'
```

**Comment by wookayin** [comment]
And what do you see in `:TSModuleInfo` output? Are only lua, vimscript, ruby supposed to be enabled?

**Comment by RRethy** [comment]
Try it now, https://github.com/RRethy/nvim-treesitter-endwise/commit/781077f9fac260dc160af347aace9002be76f45c should fix it.

In `:TSModuleInfo` I see more languages than support the `endwise` query, this is expected because certain languages like markdown can have injected languages (like lua, ruby, etc.).

Edit: Also, https://github.com/RRethy/nvim-treesitter-endwise/issues/10#issuecomment-1030941146 doesn't have enough context.

**Comment by wookayin** [comment]
Still the same error as https://github.com/RRethy/nvim-treesitter-endwise/issues/10#issuecomment-1030940828, but in a different location. This happened for me when I have run `:TSUninstall markdown`.

```
...(omitted)
        ...im/plugged/nvim-treesitter/lua/nvim-treesitter/query.lua:91: in function 'get_query'
        .../nvim-treesitter-endwise/lua/nvim-treesitter-endwise.lua:23: in function 'has_nested_endwise_language'
        .../nvim-treesitter-endwise/lua/nvim-treesitter-endwise.lua:25: in function 'has_nested_endwise_language'
```

Adding to near L23 a similar `if-check` you missed by mistake
```diff
                      if queries.has_query_files(nested_lang, 'injections') then
+                        if parsers.has_parser(nested_lang) then
+                            return false
+                        end
                         local query = queries.get_query(nested_lang, 'injections')
```
fixes the error (even when markdown or other module is not installed), and after that I do see only three ticks on ruby, vimscript, and lua as expected.

**UPDATE:** Those if-check would be better placed earlier at around L13-15:
```
14                    if queries.has_query_files(nested_lang, 'endwise') then
15                        return true
16                    end
```

I think this also would fix the latter error which seems to happen in a similar reason.

**Comment by RRethy** [comment]
Try that.

**Comment by wookayin** [comment]
I wonder if you ever tested this before making a commit or pushing. Is it something difficult for you to reproduce? There is a typo: it should be `lang` -> `nested_lang`.

**Comment by RRethy** [comment]
Thanks for the typo, your issue cannot be reproduce, now smd.
